### ISSUE TITLE
fact.io.hdureader, incomplete runs, ZSHRINK, no stderr

### ISSUE THREAD

**Issue by relleums** [fact-project/fact-tools#219]
At least for the following runs:
20170124_093
20170123_185
20170105_047
I found that the fact-tools output has only 1/2 of the expected events. Usually this numbers are exact agreement with the run-info database. There was no stderror written by fact-tools for these runs.

I take only the trigger types 4=physics, 1024=pedestal, 1=ext1 gps, and 2=ext2 gps into account.
It looks like we can not read the address table when there are too many events and shrinking kicks in.

| night | run |expected triggers | actual triggers | 3rd HDU ZSHRINK | status |
|---|---|---|---|---|---|
|20170124|093|48747|24375| 2 | incomplete |
|20170123|185|50066|25030| 2 | incomplete |
|20170123|047|57440|28725| 2 | incomplete |
|20170126|197|17835|17835| 1 | ok |

```python
In [23]: fits.open('23/20170123_047.fits.fz')[2].header['ZSHRINK']
Out[23]: 2

In [24]: fits.open('26/20170126_197.fits.fz')[2].header['ZSHRINK']
Out[24]: 1
```

**Comment by dneise** [comment]
There is a line in BinTable.java:

    numberOfRowsInTable = header.getInt(“NAXIS2“).orElse(0);

I fear, NAXIS2 is not the number of events in a file if ZSHRINK is != 1.

So the reader is happyly reading the first half of the file, and then stopping, since it read as many events it thought it should read. No stderr, from its view all is fine.

Maybe one can check this hypothesis, and find a number in the header, which gives the true number of events.

Maybe ZNAXIS2 ?

**Comment by dneise** [comment]
Unit tests on the short files we provide for testing, cannot find such a bug, since the files we provide are just a few bytes cut off a real file. So no unit test may read until the end of file...

Also artificially created zfits files containing ony a small number of events (assuming we had a zfits writer at hand) would not set ZSHRINK != 1, ... 

So testing this the way you did, ist maybe the only way...

**Comment by relleums** [comment]
Indeed for 20170124_093 the value if ```ZNAXIS2``` is 48791 which is close to the expected number of events.

**Comment by MaxNoe** [comment]
I checked #223 with file 20170123_047 and I find 42331  events. That's strange.

**Comment by relleums** [comment]
I can not reproduce my 'expected event numbers'. I do not know what I did to get these. Since you found a match with the expected number of events in the database, I would say your numbers are correct and I did sth. wrong although I thought to be doing exactly what you did.
