### ISSUE TITLE
Remove unused, untested processors

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/fact-tools#294]
- [ ] `fact.features.source.SourceLineTest` 
  * after an idea by W. Rhode) ;-)
  *  implemented by J. Freiwald in 2013
  *  code not readable, not commented, not tested))

- [ ] `fact.extraction.TimeGradientExtraction` 
  * implemented by F. Temme, not used, not tested

- [ ] `fact.cleaning.MotionCleaning` implemented by Lena in 2015, not used, not tested.

- [ ] `fact.cleaning.ProbabilityCleaning` implemented by @ftemme in 2014, not used, not tested, not working (no `@Parameter` for the input and output keys

- [ ]  `fact.features.FillAverageTimeWidth`, missing `@Parameter` for the keys, no docs, not tested, not used.

**Comment by jebuss** [comment]
I  would vote for keeping those but adding unit tests and maybe find some to evaluate those. 

`fact.features.source.SourceLineTest` is a cleaning method suggested by wolfgang. I think it was a good idea but it was never investigate further due to other priorities at that time. Could be an interesting BA.

`fact.extraction.TimeGradientExtraction` was an Idea for time extraction improvemment based on Sabrinas MA. Same as above.

`fact.extraction.TimeOverThresholdTL` is a nice tool if you want to investigate what is happening on you time series above a given threshold.  However, I agree it would make sense to have an example for this. I think it would not hurt to keep it. Nevertheless, I also don't use it anymore.

**Comment by MaxNoe** [comment]
@jebuss The reasons you state would be reasons for me to go forward removing those processors.

The code of `SourceLineTest` is not readable and the actual idea is not mentioned anywhere. It also looks like it doesn't work any more.

**Comment by MaxNoe** [comment]
Oh, the `TimeOverThresholdTL` Processor actually head an example, so I keep it. But tests and better docs would be nice to have.

**Comment by MaxNoe** [comment]
I added three more Processors (all cleaning)

**Comment by MaxNoe** [comment]
@jebuss please comment
